### ISSUE TITLE
When I run the train.py, I get a problem "RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM"

### ISSUE THREAD

**Issue by liveway6** [harryhan618/SCNN_Pytorch#22]
Train Epoch: 0
  0%|                                                  | 0/5555 [00:00<?, ?it/s]/home/anaconda3/envs/pytorch10/lib/python3.6/site-packages/torch/nn/parallel/_functions.py:61: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
batch loss: 3807.672:   1%|▏                | 72/5555 [03:03<2:11:50,  1.44s/it]THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch-nightly_1542358707753/work/aten/src/THC/THCTensorCopy.cu line=205 error=59 : device-side assert triggered
/opt/conda/conda-bld/pytorch-nightly_1542358707753/work/aten/src/THCUNN/BCECriterion.cu:42THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch-nightly_1542358707753/work/aten/src/THC/THCTensorCopy.cu line=205 error=59 : device-side assert triggered
: Acctype bce_functor<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference<float>, thrust::device_reference<float>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [0,0,0], thread: [0,0,0] Assertion `input >= 0. && input <= 1.` failed.
/opt/conda/conda-bld/pytorch-nightly_1542358707753/work/aten/src/THCUNN/BCECriterion.cu:42: Acctype bce_functor<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference<float>, thrust::device_reference<float>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [0,0,0], thread: [1,0,0] Assertion `input >= 0. && input <= 1.` failed.
/opt/conda/conda-bld/pytorch-nightly_1542358707753/work/aten/src/THCUNN/BCECriterion.cu:42: Acctype bce_functor<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference<float>, thrust::device_reference<float>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [0,0,0], thread: [2,0,0] Assertion `input >= 0. && input <= 1.` failed.
/opt/conda/conda-bld/pytorch-nightly_1542358707753/work/aten/src/THCUNN/BCECriterion.cu:42: Acctype bce_functor<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference<float>, thrust::device_reference<float>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [0,0,0], thread: [3,0,0] Assertion `input >= 0. && input <= 1.` failed.
/opt/conda/conda-bld/pytorch-nightly_1542358707753/work/aten/src/THCUNN/BCECriterion.cu:42: Acctype bce_functor<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference<float>, thrust::device_reference<float>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [0,0,0], thread: [4,0,0] Assertion `input >= 0. && input <= 1.` failed.
/opt/conda/conda-bld/pytorch-nightly_1542358707753/work/aten/src/THCUNN/BCECriterion.cu:42: Acctype bce_functor<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference<float>, thrust::device_reference<float>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [0,0,0], thread: [5,0,0] Assertion `input >= 0. && input <= 1.` failed.
/opt/conda/conda-bld/pytorch-nightly_1542358707753/work/aten/src/THCUNN/BCECriterion.cu:42: Acctype bce_functor<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference<float>, thrust::device_reference<float>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [0,0,0], thread: [6,0,0] Assertion `input >= 0. && input <= 1.` failed.
/opt/conda/conda-bld/pytorch-nightly_1542358707753/work/aten/src/THCUNN/BCECriterion.cu:42: Acctype bce_functor<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference<float>, thrust::device_reference<float>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [0,0,0], thread: [7,0,0] Assertion `input >= 0. && input <= 1.` failed.
Traceback (most recent call last):
  File "/home/code/CULane/SCNN_Pytorch/train.py", line 221, in <module>
    main()
  File "/home/code/CULane/SCNN_Pytorch/train.py", line 213, in main
    train(epoch)
  File "/home/code/CULane/SCNN_Pytorch/train.py", line 85, in train
    seg_pred, exist_pred, loss_seg, loss_exist, loss = net(img, segLabel, exist)
  File "/home/anaconda3/envs/pytorch10/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/pytorch10/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 143, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/anaconda3/envs/pytorch10/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/anaconda3/envs/pytorch10/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/home/anaconda3/envs/pytorch10/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/home/anaconda3/envs/pytorch10/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/code/CULane/SCNN_Pytorch/model.py", line 34, in forward
    x = self.message_passing_forward(x)
  File "/home/code/CULane/SCNN_Pytorch/model.py", line 57, in message_passing_forward
    x = self.message_passing_once(x, ms_conv, v, r)
  File "/home/code/CULane/SCNN_Pytorch/model.py", line 80, in message_passing_once
    out.append(slices[i] + F.relu(conv(out[i - 1])))
  File "/home/anaconda3/envs/pytorch10/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/pytorch10/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 313, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM

I have no idea to solve this problem, can you give me some advises? Looking forward to your reply.

**Comment by harryhan618** [comment]
Could you please provide your working environment? cuda version, cudnn version, pytorch version

**Comment by liveway6** [comment]
Thank you for your reply. My environment as follows:
CUDA Version 9.2.88
pytorch vesion 1.0.0.dev20181116

When I use the order "cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2" to check the cudnn vesion, but I get the result "cat: /usr/local/cuda/include/cudnn.h: No such file or directory". I am not sure the cudnn vesion.

**Comment by harryhan618** [comment]
I think there's something wrong with your cudnn library. Sorry you have to fix it yourself.

**Comment by liveway6** [comment]
Sorry to bother you again. 
When I run "test_CULane.py" with your trained model "exp10_best.pth", I get the results as follows:

loading /home/code/CULane/SCNN_Pytorch/experiments/exp10/exp10_best.pth ...... From Epoch:  13
  0%|                                                   | 0/542 [00:00<?, ?it/s]/home/anaconda3/envs/pytorch10/lib/python3.6/site-packages/torch/nn/parallel/_functions.py:61: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
100%|█████████████████████████████████████████| 542/542 [16:35<00:00,  1.65s/it]
------------Configuration---------
anno_dir: /home/data/CULane/
detect_dir: /home/code/CULane/SCNN_Pytorch/experiments/exp10/coord_output
im_dir: /home/data/CULane/
list_im_file: /home/data/CULane//list/test_split/test0_normal.txt
width_lane: 30
iou_threshold: 0.5
im_width: 1640
im_height: 590
-----------------------------------
Evaluating the results...
tp: 0 fp: 0 fn: 32777
no positive detection
finished process file
precision: -1
recall: 0
Fmeasure: 0
----------------------------------
------------Configuration---------
anno_dir: /home//data/CULane/
detect_dir: /home//code/CULane/SCNN_Pytorch/experiments/exp10/coord_output
im_dir: /home/data/CULane/
list_im_file: /home/data/CULane//list/test_split/test1_crowd.txt
width_lane: 30
iou_threshold: 0.5
im_width: 1640
im_height: 590
-----------------------------------
Evaluating the results...
tp: 0 fp: 0 fn: 28003
no positive detection
finished process file
precision: -1
recall: 0
Fmeasure: 0
----------------------------------
------------Configuration---------
anno_dir: /home/data/CULane/
detect_dir: /home/code/CULane/SCNN_Pytorch/experiments/exp10/coord_output
im_dir: /home/data/CULane/
list_im_file: /home/data/CULane//list/test_split/test2_hlight.txt
width_lane: 30
iou_threshold: 0.5
im_width: 1640
im_height: 590
-----------------------------------
Evaluating the results...
tp: 0 fp: 0 fn: 1685
no positive detection
finished process file
precision: -1
recall: 0
Fmeasure: 0
----------------------------------
------------Configuration---------
anno_dir: /home/data/CULane/
detect_dir: /home/code/CULane/SCNN_Pytorch/experiments/exp10/coord_output
im_dir: /home/data/CULane/
list_im_file: /home/data/CULane//list/test_split/test3_shadow.txt
width_lane: 30
iou_threshold: 0.5
im_width: 1640
im_height: 590
-----------------------------------
Evaluating the results...
tp: 0 fp: 0 fn: 2876
no positive detection
finished process file
precision: -1
recall: 0
Fmeasure: 0
----------------------------------
------------Configuration---------
anno_dir: /home/data/CULane/
detect_dir: /home/code/CULane/SCNN_Pytorch/experiments/exp10/coord_output
im_dir: /home/data/CULane/
list_im_file: /home/data/CULane//list/test_split/test4_noline.txt
width_lane: 30
iou_threshold: 0.5
im_width: 1640
im_height: 590
-----------------------------------
Evaluating the results...
tp: 0 fp: 0 fn: 14021
no positive detection
finished process file
precision: -1
recall: 0
Fmeasure: 0
----------------------------------
------------Configuration---------
anno_dir: /home/data/CULane/
detect_dir: /home/code/CULane/SCNN_Pytorch/experiments/exp10/coord_output
im_dir: /home/data/CULane/
list_im_file: /home/data/CULane//list/test_split/test5_arrow.txt
width_lane: 30
iou_threshold: 0.5
im_width: 1640
im_height: 590
-----------------------------------
Evaluating the results...
tp: 0 fp: 0 fn: 3182
no positive detection
finished process file
precision: -1
recall: 0
Fmeasure: 0
----------------------------------
------------Configuration---------
anno_dir: /home/data/CULane/
detect_dir: /home/code/CULane/SCNN_Pytorch/experiments/exp10/coord_output
im_dir: /home/data/CULane/
list_im_file: /home/data/CULane//list/test_split/test6_curve.txt
width_lane: 30
iou_threshold: 0.5
im_width: 1640
im_height: 590
-----------------------------------
Evaluating the results...
tp: 0 fp: 0 fn: 1312
no positive detection
finished process file
precision: -1
recall: 0
Fmeasure: 0
----------------------------------
------------Configuration---------
anno_dir: /home/data/CULane/
detect_dir: /home/code/CULane/SCNN_Pytorch/experiments/exp10/coord_output
im_dir: /home/data/CULane/
list_im_file: /home/data/CULane//list/test_split/test7_cross.txt
width_lane: 30
iou_threshold: 0.5
im_width: 1640
im_height: 590
-----------------------------------
Evaluating the results...
tp: 0 fp: 0 fn: 0
no positive detection
no ground truth positive
finished process file
precision: -1
recall: -1
Fmeasure: -1
----------------------------------
------------Configuration---------
anno_dir: /home/data/CULane/
detect_dir: /home/code/CULane/SCNN_Pytorch/experiments/exp10/coord_output
im_dir: /home/data/CULane/
list_im_file: /home/CULane//list/test_split/test8_night.txt
width_lane: 30
iou_threshold: 0.5
im_width: 1640
im_height: 590
-----------------------------------
Evaluating the results...
tp: 0 fp: 0 fn: 21030
no positive detection
finished process file
precision: -1
recall: 0
Fmeasure: 0
----------------------------------

Process finished with exit code 0

The results are wrong?

**Comment by harryhan618** [comment]
Thanks for the report! It's due to the wrong path format in `utils/lane_evaluation/CULane/Run.sh`. Please pull the new code repo. I think it would work fine.

**Comment by liveway6** [comment]
I tried it and it works!
Thank you very much.

**Comment by foxkw** [comment]
> Train Epoch: 0
> 0%| | 0/5555 [00:00<?, ?it/s]/home/anaconda3/envs/pytorch10/lib/python3.6/site-packages/torch/nn/parallel/_functions.py:61: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
> warnings.warn('Was asked to gather along dimension 0, but all '
> batch loss: 3807.672: 1%|▏ | 72/5555 [03:03<2:11:50, 1.44s/it]THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch-nightly_1542358707753/work/aten/src/THC/THCTensorCopy.cu line=205 error=59 : device-side assert triggered
> /opt/conda/conda-bld/pytorch-nightly_1542358707753/work/aten/src/THCUNN/BCECriterion.cu:42THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch-nightly_1542358707753/work/aten/src/THC/THCTensorCopy.cu line=205 error=59 : device-side assert triggered
> : Acctype bce_functor<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference, thrust::device_reference, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [0,0,0], thread: [0,0,0] Assertion `input >= 0. && input <= 1.` failed.
> /opt/conda/conda-bld/pytorch-nightly_1542358707753/work/aten/src/THCUNN/BCECriterion.cu:42: Acctype bce_functor<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference, thrust::device_reference, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [0,0,0], thread: [1,0,0] Assertion `input >= 0. && input <= 1.` failed.
> /opt/conda/conda-bld/pytorch-nightly_1542358707753/work/aten/src/THCUNN/BCECriterion.cu:42: Acctype bce_functor<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference, thrust::device_reference, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [0,0,0], thread: [2,0,0] Assertion `input >= 0. && input <= 1.` failed.
> /opt/conda/conda-bld/pytorch-nightly_1542358707753/work/aten/src/THCUNN/BCECriterion.cu:42: Acctype bce_functor<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference, thrust::device_reference, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [0,0,0], thread: [3,0,0] Assertion `input >= 0. && input <= 1.` failed.
> /opt/conda/conda-bld/pytorch-nightly_1542358707753/work/aten/src/THCUNN/BCECriterion.cu:42: Acctype bce_functor<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference, thrust::device_reference, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [0,0,0], thread: [4,0,0] Assertion `input >= 0. && input <= 1.` failed.
> /opt/conda/conda-bld/pytorch-nightly_1542358707753/work/aten/src/THCUNN/BCECriterion.cu:42: Acctype bce_functor<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference, thrust::device_reference, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [0,0,0], thread: [5,0,0] Assertion `input >= 0. && input <= 1.` failed.
> /opt/conda/conda-bld/pytorch-nightly_1542358707753/work/aten/src/THCUNN/BCECriterion.cu:42: Acctype bce_functor<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference, thrust::device_reference, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [0,0,0], thread: [6,0,0] Assertion `input >= 0. && input <= 1.` failed.
> /opt/conda/conda-bld/pytorch-nightly_1542358707753/work/aten/src/THCUNN/BCECriterion.cu:42: Acctype bce_functor<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference, thrust::device_reference, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [0,0,0], thread: [7,0,0] Assertion `input >= 0. && input <= 1.` failed.
> Traceback (most recent call last):
> File "/home/code/CULane/SCNN_Pytorch/train.py", line 221, in
> main()
> File "/home/code/CULane/SCNN_Pytorch/train.py", line 213, in main
> train(epoch)
> File "/home/code/CULane/SCNN_Pytorch/train.py", line 85, in train
> seg_pred, exist_pred, loss_seg, loss_exist, loss = net(img, segLabel, exist)
> File "/home/anaconda3/envs/pytorch10/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/anaconda3/envs/pytorch10/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 143, in forward
> outputs = self.parallel_apply(replicas, inputs, kwargs)
> File "/home/anaconda3/envs/pytorch10/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in parallel_apply
> return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
> File "/home/anaconda3/envs/pytorch10/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
> raise output
> File "/home/anaconda3/envs/pytorch10/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
> output = module(*input, **kwargs)
> File "/home/anaconda3/envs/pytorch10/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/code/CULane/SCNN_Pytorch/model.py", line 34, in forward
> x = self.message_passing_forward(x)
> File "/home/code/CULane/SCNN_Pytorch/model.py", line 57, in message_passing_forward
> x = self.message_passing_once(x, ms_conv, v, r)
> File "/home/code/CULane/SCNN_Pytorch/model.py", line 80, in message_passing_once
> out.append(slices[i] + F.relu(conv(out[i - 1])))
> File "/home/anaconda3/envs/pytorch10/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/anaconda3/envs/pytorch10/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 313, in forward
> self.padding, self.dilation, self.groups)
> RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM
> 
> I have no idea to solve this problem, can you give me some advises? Looking forward to your reply.

Hi, I have the same question , How did you solve it ?
