### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by lilyzhng** [harryhan618/SCNN_Pytorch#24]
Hi Harry, 

Could you clarify how many GBs memory and graphics card is used to training CULane and TuSimple?

I have 64GB memory and RTX 2080 TI, but got the out of memory issue.

Thanks,
Lily

**Comment by harryhan618** [comment]
Hello! I remember I used 4 or 8 GPUs with total batchsize of 64 or 128 for training. It happened to me to get access to large computing resources so I tried  the experiments with this heavy configuration. I think it would also work well with total batchsize of 16 or 32. 
Note that if your batchsize is getting smaller, the learning rate has to be smaller as well. Or it may not converge or result to a good model.

**Comment by lilyzhng** [comment]
@harryhan618 Thanks for the reply, I reduced the batch size from 256 to 8, and it works now.  In my case, the original lr is 16e-2, do you know what could be a good learning rate to go with now?

**Comment by lilyzhng** [comment]
"Theory suggests that when multiplying the batch size by k, one should multiply the learning rate by sqrt(k)" or "Multiply your learning rate by k when using mini-batch size of kN" from https://stackoverflow.com/questions/53033556/how-should-the-learning-rate-change-as-the-batch-size-change.

I found some recommendations on stackoverflow, but still would like to have your suggestions as well. 
![image](https://user-images.githubusercontent.com/10191088/66955484-45f35600-f017-11e9-9fd4-1810f8dd1d53.png)

**Comment by harryhan618** [comment]
Maybe 5e-3?

**Comment by lilyzhng** [comment]
Will try, thanks.
